version: '3.8'

services:
  test-task:
    container_name: test-task
    build: ./
    command: ./bin
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  db:
    restart: unless-stopped
    image: postgres
    volumes:
      # до доветочия - директива куда будут сохраняться данные, после - путь до папки в контейнере
      - ./data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"